### ISSUE TITLE
有个收款码主题合并有BUG

### ISSUE THREAD

**Issue by gimgoo** [insoxin/weapp-qrpay#2]
![Screen Shot 2019-09-03 at 14 45 33](https://user-images.githubusercontent.com/31849284/64149815-8d53c780-ce59-11e9-840b-d7ff948e72eb.png)
这个无法生成，是个BUG，其他都没问题，Chrome，Safari，安卓版Chrome都是一个结果

**Comment by insoxin** [comment]
感谢反馈,已修复,后续问题可去https://github.com/insoxin/qrpay/issues提交
