### ISSUE TITLE
请教下imaotai的Client_Secret如何获取

### ISSUE THREAD

**Issue by irvineyang** [insoxin/weapp-qrpay#4]
很抱歉在这个项目下发起Issues，因为imaotai的项目发起不了。
我想请教下imaotai这个APP的Client_Secret是怎么获取的？
我用Fiddler抓取iphone上的APP数据，没能找到Client_Secret。
有一些TLS加密的请求我无法看到明文，不知道是不是藏在里面，但是我没有能力解码。
恳求赐教，谢谢！

**Comment by TlyJ** [comment]
请问解决了吗

**Comment by insoxin** [comment]
@TlyJ @irvineyang 你们应该不是从我博客看到的
https://blog.isoyu.com/archives/imaotaimt-device-idmt-r-md5jiajiemi.html

可以看下这篇

另外不推荐使用了,这个只能抢到一次,之后就没资格了,官方做了限制.还不如手动,这个自动抢就是个累赘,所以这个老板找我订做后跑单了,我自发布后也未再更新
